name: Open-Source, Robotics, ...
description: Open-Source Solutions in Robotics and more
url: http://andreasBihlmaier.github.io
timezone: Europe/Berlin
encoding: UTF-8
pygments: true
markdown: kramdown
